### ISSUE TITLE
bitmonerod: armv7: segfault in mdb_cursor_unref with max-concurrency > 1

### ISSUE THREAD

**Issue by radfish** [monero-project/monero#1001]
Commit 16e9dbc

Segfault happened while catching up from about 99.6% sync status.

```
(gdb) bt
#0  0x0035540c in mdb_cursor_unref ()
#1  0x00355384 in mdb_page_unref.isra ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

[thread apply all bt](https://github.com/monero-project/bitmonero/files/441650/bt.txt)

Core file available. Will try to replicate in a debug build.

**Comment by radfish** [comment]
looks like `max-concurrency 1` prevents this. It must be the same problem I reported earlier in a random comment somewhere. At the time I did not get a core, and it was not reproducible inside gdb. Now I have a core.

**Comment by radfish** [comment]
Been running for weeks on armv7h without amx-concurrency=1 fine.
