### ISSUE TITLE
Segmentation fault when running unit_tests

### ISSUE THREAD

**Issue by iDunk5400** [monero-project/monero#1057]
Running unit_tests (afe3cce, release) fails with a segmentation fault in `ringct.range_proofs_reject_empty_ins`. Monero was built with gcc 6.2.0 and boost 1.61, but the segfault also happens when building with gcc 4.9.3 and boost 1.58.

```
./build/release/tests/unit_tests/unit_tests 
Creating the logger system
[==========] Running 620 tests from 57 test cases.
[----------] Global test environment set-up.
[----------] 2 tests from select_outputs
[ RUN      ] select_outputs.one_out_of_N
[       OK ] select_outputs.one_out_of_N (1 ms)
[ RUN      ] select_outputs.order
[       OK ] select_outputs.order (0 ms)
[----------] 2 tests from select_outputs (1 ms total)

[----------] 136 tests from ringct
[ RUN      ] ringct.SNL
[       OK ] ringct.SNL (4 ms)
[ RUN      ] ringct.ASNL
[       OK ] ringct.ASNL (309 ms)
[ RUN      ] ringct.MG_sigs
[       OK ] ringct.MG_sigs (27 ms)
[ RUN      ] ringct.range_proofs
[       OK ] ringct.range_proofs (420 ms)
[ RUN      ] ringct.range_proofs_with_fee
[       OK ] ringct.range_proofs_with_fee (420 ms)
[ RUN      ] ringct.simple
[       OK ] ringct.simple (208 ms)
[ RUN      ] ringct.range_proofs_reject_empty_outs
[       OK ] ringct.range_proofs_reject_empty_outs (10 ms)
[ RUN      ] ringct.range_proofs_reject_empty_outs_simple
[       OK ] ringct.range_proofs_reject_empty_outs_simple (11 ms)
[ RUN      ] ringct.range_proofs_reject_empty_ins
Segmentation fault (core dumped)
```

```
gdb build/release/tests/unit_tests/unit_tests core
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from build/release/tests/unit_tests/unit_tests...done.
[New LWP 16881]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./build/release/tests/unit_tests/unit_tests'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000564184 in std::vector<std::vector<crypto::signature, std::allocator<crypto::signature> >, std::allocator<std::vector<crypto::signature, std::allocator<crypto::signature> > > >::~vector() [clone .lto_priv.2475] ()
(gdb) thread apply all bt

Thread 1 (Thread 0x7f81b8a3d780 (LWP 16881)):
#0  0x0000000000564184 in std::vector<std::vector<crypto::signature, std::allocator<crypto::signature> >, std::allocator<std::vector<crypto::signature, std::allocator<crypto::signature> > > >::~vector() [clone .lto_priv.2475] ()
#1  0x000000000070a99d in rct::genRct(rct::key const&, std::vector<rct::ctkey, std::allocator<rct::ctkey> > const&, std::vector<rct::ctkey, std::allocator<rct::ctkey> > const&, std::vector<rct::key, std::allocator<rct::key> > const&, std::vector<unsigned long, std::allocator<unsigned long> > const&, std::vector<rct::key, std::allocator<rct::key> > const&, int) ()
#2  0x00000000006a0b3e in make_sample_rct_sig(int, unsigned long const*, int, unsigned long const*, bool) [clone .lto_priv.2478] ()
#3  0x00000000009a8867 in range_proof_test(bool, int, unsigned long const*, int, unsigned long const*, bool, bool) [clone .constprop.822] ()
#4  0x000000000068fb25 in ringct_range_proofs_reject_empty_ins_Test::TestBody() ()
#5  0x00000000009bc96d in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [clone .constprop.42] ()
#6  0x0000000000920143 in testing::Test::Run() [clone .part.492] ()
#7  0x000000000092639f in testing::TestInfo::Run() [clone .part.493] ()
#8  0x0000000000926705 in testing::TestCase::Run() [clone .part.494] ()
#9  0x0000000000927aa3 in testing::internal::UnitTestImpl::RunAllTests() [clone .part.507] ()
#10 0x0000000000927f73 in testing::UnitTest::Run() ()
#11 0x00000000005196de in main ()
(gdb) 
```

**Comment by iDunk5400** [comment]
Caused by linking against libunwind. Excluding (uninstalling, in my case) libunwind solved the problem.
