### ISSUE TITLE
OpenBSD memory leak? Corruption? Readline?

### ISSUE THREAD

**Issue by mrme0w** [monero-project/monero#5570]
[wallet 4AsDPc (no daemon)]: save
��������������������������������@XI�bWallet data saved
[wallet 4AsDPc (no daemon)]: save
��������������������������������Wallet data saved
[wallet 4AsDPc (no daemon)]: save
���������������������������������7�aWallet data saved
[wallet 4AsDPc (no daemon)]: save
[wallet 4AsDPc (no daemon)]: Segmentation fault (core dumped)

**Comment by mrme0w** [comment]
(Notice the strange artifacts that change after all of the question marks)

Next post is a gdb backtrace

**Comment by mrme0w** [comment]
(gdb) bt
#0  strrchr () at /usr/src/lib/libc/arch/amd64/string/strrchr.S:51
#1  0x0000006249a96a86 in rl_redisplay () at /usr/src/gnu/lib/libreadline/display.c:454
#2  0x0000005f98ff1747 in rdln::suspend_readline::suspend_readline () from /home/mrme0w/monero/build/OpenBSD/master/release/bin/monero-wallet-cli
#3  0x0000005f98bcb759 in tools::scoped_message_writer::~scoped_message_writer () from /home/mrme0w/monero/build/OpenBSD/master/release/bin/monero-wallet-cli
#4  0x0000005f98b4c16f in cryptonote::simple_wallet::save () from /home/mrme0w/monero/build/OpenBSD/master/release/bin/monero-wallet-cli
#5  0x0000005f98bd0568 in epee::command_handler::process_command_vec () from /home/mrme0w/monero/build/OpenBSD/master/release/bin/monero-wallet-cli
#6  0x0000005f98be5957 in epee::command_handler::process_command_str () from /home/mrme0w/monero/build/OpenBSD/master/release/bin/monero-wallet-cli
#7  0x0000005f98be637c in _ZN4epee21async_console_handler3runIZNS0_3runIN5boost3_bi6bind_tIbNS3_4_mfi3mf1IbNS_15command_handlerERKNSt3__112basic_stringIcNS9_11char_traitsIcEENS9_9allocatorIcEEEEEENS4_5list2INS4_5valueIPNS_23console_handlers_binderEEENS3_3argILi1EEEEEEEEEbT_NS9_8functionIFSF_vEEESH_NST_IFvvEEEEUlSH_E_EEbSV_SH_RKSS_SX_ () from /home/mrme0w/monero/build/OpenBSD/master/release/bin/monero-wallet-cli
#8  0x0000005f98be57ea in epee::async_console_handler::run<boost::_bi::bind_t<bool, boost::_mfi::mf1<bool, epee::command_handler, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>, boost::_bi::list2<boost::_bi::value<epee::console_handlers_binder*>, boost::arg<1> > > > () from /home/mrme0w/monero/build/OpenBSD/master/release/bin/monero-wallet-cli
#9  0x0000005f98bd0267 in epee::console_handlers_binder::run_handling () from /home/mrme0w/monero/build/OpenBSD/master/release/bin/monero-wallet-cli
#10 0x0000005f98baa8d1 in cryptonote::simple_wallet::run () from /home/mrme0w/monero/build/OpenBSD/master/release/bin/monero-wallet-cli
#11 0x0000005f98bae2af in main () from /home/mrme0w/monero/build/OpenBSD/master/release/bin/monero-wallet-cli
Current language:  auto; currently asm
(gdb)

**Comment by mrme0w** [comment]
These strange console artifacts happen on monerod too, but mostly after commands such as "save" or "exit".

**Comment by mrme0w** [comment]
OK, so compiling with readline disabled on OpenBSD fixes the garbled output and crashes.

Any suggestions on how to fix this?

**Comment by moneromooo-monero** [comment]
Any chance you can rn with asan (add -D SANITIZE=ON to the cmake command line) ?

**Comment by offshoremonero** [comment]
Pull request #8596 fixes this issue for now.
