### ISSUE TITLE
segfault on exit with hydrogen helix

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero#669]
http://fpaste.org/323114/55563771/

**Comment by radfish** [comment]
Pastie is dead. In the future, please attach the file directly on github using the 'Attach file'  link in the editor (and also paste the relevant part of the log directly into the post).

I assume this is the segfault that happens consistently when sending SIGTERM (clean exit) to the daemon:

Commit: de91bb75a1669dc1d5baf5a48379cf1d63707c76
GDB on core:

```
Core was generated by `/usr/bin/bitmonerod --config-file /etc/bitmonerod.conf --detach'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00217f54 in nOT::nUtils::cLogger::Thread2Number(boost::thread::id) ()
[Current thread is 1 (Thread 0xb4aac450 (LWP 3828))]
(gdb) bt
#0  0x00217f54 in nOT::nUtils::cLogger::Thread2Number(boost::thread::id) ()
#1  0x0024c054 in nOT::nUtils::cLogger::write_stream(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .constprop.794] ()
#2  0x002b2dc0 in epee::net_utils::data_logger::saveToFile() ()
#3  0x002bb538 in epee::net_utils::data_logger::data_logger()::{lambda()#1}::operator()() const [clone .lto_priv.2260] ()
#4  0xb697ecd4 in ?? () from /usr/lib/libboost_thread.so.1.60.0
#5  0xb6cb9fbc in start_thread () from /usr/lib/libpthread.so.0
#6  0xb6c44cf0 in ?? () from /usr/lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) up
#1  0x0024c054 in nOT::nUtils::cLogger::write_stream(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .constprop.794] ()
(gdb) up
#2  0x002b2dc0 in epee::net_utils::data_logger::saveToFile() ()
(gdb) thread 2
[Switching to thread 2 (Thread 0xb4ab1000 (LWP 3827))]
#0  0x00216fd4 in nOT::nUtils::cLogger::Pid2Number(long) ()
(gdb) bt
#0  0x00216fd4 in nOT::nUtils::cLogger::Pid2Number(long) ()
#1  0x0024c080 in nOT::nUtils::cLogger::write_stream(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .constprop.794] ()
#2  0x002b7580 in epee::net_utils::data_logger::~data_logger() ()
#3  0x002efa8c in std::unique_ptr<epee::net_utils::data_logger, std::default_delete<epee::net_utils::data_logger> >::~unique_ptr() ()
#4  0xb6ba5e54 in __run_exit_handlers () from /usr/lib/libc.so.6
#5  0xb6ba5ea8 in exit () from /usr/lib/libc.so.6
#6  0xb6b8ecc0 in __libc_start_main () from /usr/lib/libc.so.6
#7  0x000aa190 in _start ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) info thread
  Id   Target Id         Frame 
  1    Thread 0xb4aac450 (LWP 3828) 0x00217f54 in nOT::nUtils::cLogger::Thread2Number(boost::thread::id) ()
* 2    Thread 0xb4ab1000 (LWP 3827) 0x00216fd4 in nOT::nUtils::cLogger::Pid2Number(long) ()
```

Looks the two threads are failing when outputing log messages via macros like _info_c(). Removing all log statements from saveToFile(), save(), and lambda in dataLogger() and ~dataLogger() does prevent the segfault.

Not sure, but maybe `cLogger` (an object with static lifetime: `cLogger gCurrentLogger`) gets destroyed before `data_logger` (a singleton created on demand, stored in a `static unique_ptr` field of a class). Probably worth a try to create `cLogger` explicitly, and keep it as a singleton, similarly to `data_logger`, instead of declaring it as a static object and hoping the init/destroy order will be correct.

**Comment by Gingeropolous** [comment]
I haven't seen my monerod segfault on exit for a while. I can close this issue unless others are still seeing segfaults.
